/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum TranslateErrorCode {
  UNSUPPORT_OS_VERSION = 'ERR_TRANSLATE_UNSUPPORTED_OS_VERSION',
  LANGUAGE_PAIR_NOT_INSTALLED = 'ERR_TRANSLATE_LANGUAGE_PAIR_NOT_INSTALLED',
  FAILED = 'ERR_TRANSLATE_FAILED'
}
/**
 * Translate text with the system's installed language models.
 *
 * Rejects with an Error whose code is one of:
 * `ERR_TRANSLATE_UNSUPPORTED_OS_VERSION`,
 * `ERR_TRANSLATE_LANGUAGE_PAIR_NOT_INSTALLED`, or `ERR_TRANSLATE_FAILED`.
 */
export declare function translateText(text: string, targetLang: string): Promise<unknown>
/**
 * Request authorization to use speech recognition.
 * Returns "authorized" | "denied" | "restricted" | "notDetermined".
 */
export declare function requestSpeechPermission(): Promise<unknown>
export interface SpeechRecognitionOptions {
  onDeviceOnly?: boolean
}
/** Recognize speech from an audio file, optionally requiring the system's local model. */
export declare function recognizeSpeech(filePath: string, lang: string, options?: SpeechRecognitionOptions | undefined | null): Promise<unknown>
export interface SpeechRecognitionCapabilities {
  isAvailable: boolean
  supportsOnDeviceRecognition: boolean
  isAuthorized: boolean
}
/** Check whether the selected locale currently supports system speech recognition. */
export declare function getSpeechRecognitionCapabilities(lang: string): SpeechRecognitionCapabilities
