/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function translateText(text: string, targetLang: string): Promise<unknown>
/**
 * Request authorization to use speech recognition.
 * Returns "authorized" | "denied" | "restricted" | "notDetermined".
 */
export declare function requestSpeechPermission(): Promise<unknown>
/**
 * Recognize speech from an audio file using macOS Speech framework.
 * Requires prior authorization via requestSpeechPermission().
 * filePath: absolute path to audio file (WAV, M4A, FLAC, MP3, etc.)
 * lang:     BCP-47 locale, e.g. "en-US", "zh-CN"
 */
export declare function recognizeSpeech(filePath: string, lang: string): Promise<unknown>
